import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create
        next app"
        />
        <link
          rel="icon"
          href="/favicon.
        ico"
        />
      </Head>

      <div className="content-center">
        <p className="text-2xl font-bold">Nextshop</p>
        <p> Kim Minwoo</p>
        <p> - tailwindCSS</p>
        <p> - MongoDB</p>
      </div>
    </div>
  )
}
